name: Reference Frontend Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./reference_client
        run: npm install
      - name: Generate
        working-directory: ./reference_client
        run: npm run generate
        env:
          API_URL: https://api.algdb.net
          VER: "0.0.1"
          WCA_AUTH_URL: https://staging.worldcubeassociation.org/oauth/authorize?client_id=example-application-id&redirect_uri=https%3A%2F%2Falgdb-ref-client.web.app%2Fwca-redirect&response_type=code&scope=public+dob+email+manage_competitions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./reference_client
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
